#gitlab CI部署文件，切勿删除
#date: 2020-09-14
#auth: 廖发友

stages:
  - build
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "master"'

default:
  tags:
    - RunnerGroupNode-192.168.40.223-印度征信

variables:
  ENV_CUSTOM_CONFIG: "/home/gitlab-runner/config/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/config.json"
  ENV_CUSTOM_STAGE: "${CI_JOB_STAGE}"
  ENV_CUSTOM_REF_NAME: "${CI_COMMIT_REF_SLUG}"

.DefinitionBuildTemplate: &DefinitionBuildTemplate
  - mvn clean package

.ExtendsBuildArtifacts:
  artifacts:
    name:
      "$CI_COMMIT_REF_SLUG"
    paths:
      - clerk-gateway/target/clerk-gateway-*.jar
      - clerk-oauth/target/clerk-oauth-*.jar
      - .config.json
      - .md5.txt
    expire_in:
      6 hours

OnlyBuild:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: never
    - when: on_success
  script:
    - *DefinitionBuildTemplate

Build:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: on_success
  extends:
    - .ExtendsBuildArtifacts
  script:
    - *DefinitionBuildTemplate
    - cd ${CI_PROJECT_DIR}
    - sh .ci/deploy.sh

Deploy:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: on_success
  environment:
    name: deploy_$CI_COMMIT_REF_SLUG
  script:
    - sh .ci/deploy.sh
  tags:
    - RunnerGroupNode-HK-149.129.89.208-印度征信

