logging:
  level:
    root:
      info
mybatis:
  type-aliases-package: com.ps.judge.dao.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080

spring:
  application:
    name: clerk-gateway
  cloud:
    nacos:
      discovery:
        server-addr: "192.168.40.150:8848"
        cluster-name: "FS"
        metadata:
          version: "v1"
        namespace: "ecfb127e-7595-4da6-ae6b-d7f1abf4d6e8"
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      token-info-uri: http://localhost:8081/oauth/check_token
