logging:
  level:
    root:
      info
    org.springframework.cloud.gateway: trace
mybatis:
  type-aliases-package: com.ps.judge.dao.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080
spring:
  application:
    name: clerk-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8082/api/rsa/publicKey'
  cloud:
    nacos:
      discovery:
        server-addr:  ${nacos.server-addr}
        cluster-name: "FS"
        metadata:
          version: "v1"
        namespace: ${nacos.namespace}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clerk-oauth
          uri: lb://clerk-oauth
          predicates:
            - Path=/clerk-oauth/**
          filters:
            - StripPrefix=1
        - id: judge
          uri: lb://judge
          predicates:
            - Path=/judge/**
          filters:
            - StripPrefix=1
        - id: jury
          uri: lb:/jury
          predicates:
            - Path=/jury/**
          filters:
            - StripPrefix=1
        - id: witness
          uri: lb://witness
          predicates:
            - Path=/witness/**
          filters:
            - StripPrefix=1
clerk:
  security:
    notRequireAuthentication: /clerk-auth/oauth/**
    notRequireAuthorization: /clerk-auth/current/**