logging:
  level:
    root:
      info
    org.springframework.cloud.gateway: info
server:
  port: 8080
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always
spring:
  application:
    name: clerk-gateway
  jackson:
    default-property-inclusion: non_empty
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8082/rsa/publicKey'
  cloud:
    nacos:
      discovery:
        server-addr:  ${nacos.addr}
        namespace: ${nacos.namespace}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clerk-oauth
          uri: lb://clerk-oauth
          predicates:
            - Path=/clerk-oauth/**
          filters:
            - StripPrefix=1
        - id: judge
          uri: lb://judge
          predicates:
            - Path=/judge/**
          filters:
            - StripPrefix=1
        - id: jury
          uri: lb:/jury
          predicates:
            - Path=/jury/**
          filters:
            - StripPrefix=1
        - id: witness
          uri: lb://witness
          predicates:
            - Path=/witness/**
          filters:
            - StripPrefix=1
clerk:
  security:
    notRequireAuthentication: /clerk-oauth/oauth/**
    notRequireAuthorization: /clerk-oauth/current/**