logging:
  level:
    root: info
    com.wind.clerk.oauth.dao.mapper: debug
mybatis:
  type-aliases-package: com.wind.clerk.oauth.dao.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*.xml
server:
  port: 8082

spring:
  application:
    name: clerk-oauth
  jackson:
    default-property-inclusion: non_empty
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Dev@123456
    username: dev
    url: jdbc:mysql://192.168.40.147:3306/clerk-oauth?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
encrypt:
  key-store:
    alias: ps
    secret: admin123
    password: admin123
    type: jks
    location: classpath:xc.keystore

clerk-common:
  enabled: true
