logging:
  level:
    root:
      info
mybatis:
  type-aliases-package: com.wind.clerk.oauth.dao.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080

spring:
  application:
    name: clerk-oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Dev@123456
    username: dev
    url: jdbc:mysql://192.168.40.147:3306/clerk-oauth?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  cloud:
    nacos:
      discovery:
        server-addr: "192.168.40.150:8848"
        cluster-name: "FS"
        metadata:
          version: "v1"
        namespace: "ecfb127e-7595-4da6-ae6b-d7f1abf4d6e8"
